services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - 9999:8000
    volumes:
      - dynamodb-volume:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
volumes:
  dynamodb-volume: